import Link from "next/link";
import { ArrowDown, ArrowRight, ArrowUpRight, Check, FileText, GitBranch, MapPin, Sparkles, Users, Waves } from "lucide-react";
export default function Home(){return <main className="landing">
 <nav className="landing-nav"><Link href="/" className="brand"><i/>SceneAtlas</Link><div className="nav-links"><a href="#how">How it works</a><Link href="/preview">Explore the canvas</Link></div><Link href="/workspaces" className="button small-button">Open workspace <ArrowUpRight size={15}/></Link></nav>
 <section className="hero"><div className="hero-copy"><span className="eyebrow"><span className="status-dot"/> THE PRODUCTION, BEFORE THE PRODUCTION</span><h1>Every location<br/>decision.<br/><span>Evidence attached.</span></h1><p>A screenplay goes in. A researched shooting plan comes out. Bring your scenes, locations, questions, and people together on one living canvas.</p><div className="actions"><Link href="/workspaces" className="button primary large-button">Start your production <ArrowRight size={17}/></Link><Link href="/preview" className="text-link">Take a look around <ArrowUpRight size={15}/></Link></div><div className="hero-foot"><span><Users size={14}/> Made for small production teams</span><span className="quiet-line"/>Built around your screenplay</div></div>
 <div className="hero-canvas" aria-label="Illustration of a screenplay connected to scene and location cards"><div className="canvas-caption"><span className="status-dot"/> COASTAL SHORT <span>EXAMPLE WORKSPACE</span></div><svg viewBox="0 0 620 640" className="hero-wires"><path d="M300 190 C300 250 150 220 150 290M300 190 C300 250 455 220 455 290M150 425C150 470 255 450 255 495M455 425C455 480 330 450 330 495"/></svg><div className="hero-card script-preview"><div className="card-icon"><FileText size={18}/></div><div><span className="eyebrow">THE SCREENPLAY</span><h3>coastal_short.pdf</h3><p>Scene breakdown · saved answers</p></div><span className="badge brass-badge">Script root</span></div><div className="hero-card scene-preview one"><span className="eyebrow">SCENE 01</span><h3>Where the land ends.</h3><p>EXT. BEACH — DAY</p><div className="small-divider"/><span className="sample-excerpt">“Mara crosses the open sand toward the rocks…”</span><span className="badge moss-badge"><Check size={12}/> Production choices saved</span></div><div className="hero-card scene-preview two"><span className="eyebrow">SCENE 02</span><h3>The last light.</h3><p>EXT. CLIFF — DUSK</p><div className="small-divider"/><div className="mini-question">Is golden hour essential?</div><div className="chip-row"><span className="chip brass-badge">Essential</span><span className="chip">Flexible</span></div></div><div className="hero-card location-preview"><div className="location-illustration"><Waves size={44}/><span>LOCATION RESEARCH</span></div><div><h3>One location. Two scenes.</h3><p><MapPin size={12}/> Shared evidence, connected decisions</p><span className="badge moss-badge">Sources stay attached <ArrowUpRight size={12}/></span></div></div><div className="canvas-corner"><span>−</span> 80% <span>+</span></div></div>
 </section><div className="evidence-strip"><span>Nothing important gets lost between tabs.</span><div><span><i className="dot moss"/> Sourced</span><span><i className="dot brass"/> Estimated</span><span><i className="dot clay"/> Still unknown</span></div><a href="#how" aria-label="See how it works"><ArrowDown size={17}/></a></div>
 <section className="how-section" id="how"><div className="section-kicker">FROM FIRST READ TO READY TO REVIEW</div><h2>Follow the story.<br/><span>Build the production around it.</span></h2><div className="steps-grid">{[{icon:FileText,n:"01",title:"Start with the screenplay",text:"Drop your PDF. Find the scenes, preserve the original excerpts, and answer the questions that matter."},{icon:MapPin,n:"02",title:"Explore with evidence",text:"Research real locations. Keep creative fit, known fees, access restrictions, and open questions in view."},{icon:GitBranch,n:"03",title:"Choose your tradeoffs",text:"Compare a budget plan and a creative plan. Change one decision and see exactly what it affects."},{icon:Users,n:"04",title:"Move forward together",text:"Invite your team to work or watch. Export a preparation packet with sources and unknowns carried through."}].map(({icon:Icon,n,title,text})=><article key={n}><div><Icon size={23}/><span>{n}</span></div><h3>{title}</h3><p>{text}</p></article>)}</div></section>
 <section className="landing-cta glass"><Sparkles size={25}/><h2>Your next shoot starts<br/>with a clearer picture.</h2><Link href="/workspaces" className="button primary">Create a workspace <ArrowRight size={16}/></Link><p>Research and preparation. Every unknown stays visible.</p></section><footer className="landing-footer"><Link className="brand" href="/"><i/>SceneAtlas</Link><span>From screenplay to a researched shooting plan.</span><span>Made for the decisions before “action.”</span></footer>
</main>;}
